#!/usr/bin/env bash

set -o errexit

#
# Helpers
#
time-now() {
  date +%s.%N
}
benchmark() {
  local start=$1
  local end=${2:-$(time-now)}
  printf %.2f $(echo "$end - $start" | bc -l)
}

#
# Main
#
DIR=$(pwd)
URL=$1
BASENAME=$(basename $URL | sd '\?.*' '')
OUTPUT=${2:-$BASENAME}
TEMPFILE=$(mktemp)
TEMPDIR=$(mktemp -d)
# echo "Downloading: $OUTPUT ..."

cd $TEMPDIR

curl \
  -# \
  --location \
  --keepalive \
  --connect-timeout 5 \
  --retry 1 \
  --fail \
  --compressed \
  -o "$OUTPUT" \
  "${URL}" 2>&1

# wget \
#   --compression auto \
#   -O $OUTPUT \
#   -q \
#   --show-progress \
#   --progress=bar:noscroll \
#   "${URL}" \
#   2>&1

cd $DIR

mv ${TEMPDIR}/* $PWD/$OUTPUT

echo "✅ $URL"
